packages:
  - packages/*
catalog:
  '@dotenvx/dotenvx': ^1.14.0
  '@eslint/js': ^9.10.0
  '@faker-js/faker': ^9.0.0
  '@tsconfig/node22': ^22.0.0
  '@tsconfig/recommended': ^1.0.7
  '@types/config': ^3.3.5
  '@types/eslint__js': ^8.42.3
  '@types/node': ^22.5.4
  ajv: ^8.17.1
  config: ^3.3.12
  eslint: ^9.10.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-markdown: ^5.1.0
  eslint-plugin-prettier: ^5.2.1
  globals: ^15.9.0
  husky: ^9.1.5
  jest: ^29.7.0
  moment: ^2.30.1
  nodemon: ^3.1.4
  pino: ^9.4.0
  pino-pretty: ^11.2.2
  prettier: ^3.3.3
  prettier-plugin-organize-imports: ^4.0.0
  ts-jest: ^29.2.5
  ts-node: ^10.9.2
  tsc-alias: ^1.8.10
  tsconfig-paths: ^4.2.0
  tslib: ^2.7.0
  typescript: ^5.5.4
  typescript-eslint: ^8.4.0
catalogs:
  api:
    fastify: ^4.28.1
  web-app:
    react: ^18.3.1
    react-dom: ^18.3.1
    react-router-dom: ^6.26.1
